# =============================================================================
# Docker Compose - Development Environment
# =============================================================================
# Configuração para desenvolvimento local usando as imagens xCloud
# Use: docker-compose up -d
# =============================================================================
version: '3.8'

services:
  # Serviço de aplicação Node.js
  nodejs-app:
    image: ghcr.io/pagecloudv1/xcloud-nodejs:latest
    container_name: xcloud-nodejs-dev
    volumes:
      # Monta o código da aplicação
      - ../examples/nodejs-app:/home/xcloud/app
      # Persiste node_modules
      - nodejs-modules:/home/xcloud/app/node_modules
    working_dir: /home/xcloud/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - xcloud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço de aplicação Python
  python-app:
    image: ghcr.io/pagecloudv1/xcloud-python:latest
    container_name: xcloud-python-dev
    volumes:
      # Monta o código da aplicação
      - ../examples/python-app:/home/xcloud/app
      # Persiste pacotes Python
      - python-packages:/home/xcloud/.local
    working_dir: /home/xcloud/app
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    networks:
      - xcloud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx como reverse proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: xcloud-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - nodejs-app
      - python-app
    networks:
      - xcloud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  xcloud-network:
    driver: bridge
    name: xcloud-dev-network

volumes:
  nodejs-modules:
    name: xcloud-nodejs-modules
  python-packages:
    name: xcloud-python-packages
