# =============================================================================
# Workflow: Publish Node.js Image
# =============================================================================
# Builds and publishes the xcloud-nodejs container image to ghcr.io.
# This workflow is triggered on pushes to the 'main' branch when files
# in the 'nodejs/' directory are changed.
# =============================================================================
name: 'Publish - Node.js Image'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nodejs/**'
      - 'base/**' # Rebuild if the base image changes

  workflow_dispatch:

jobs:
  publish-nodejs-image:
    uses: ./.github/workflows/reusable-build-publish.yml@main@main
    with:
      image_name: 'xcloud-nodejs'
      dockerfile_path: './nodejs/Podmanfile'
      build_context: './nodejs'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
