# =============================================================================
# Reusable Workflow: Build and Publish Container Image
# =============================================================================
# This workflow builds a container image using Podman/Docker and publishes it
# to the GitHub Container Registry (ghcr.io).
#
# It is designed to be called by other workflows.
# =============================================================================
name: 'Reusable - Build and Publish Image'

on:
  workflow_call:
    inputs:
      image_name:
        description: 'The name of the image to build (e.g., xcloud-base)'
        required: true
        type: string
      image_tag:
        description: 'The tag for the image (defaults to "latest")'
        required: false
        type: string
        default: 'latest'
      dockerfile_path:
        description: 'The path to the Podmanfile/Dockerfile'
        required: true
        type: string
      build_context:
        description: 'The build context path (defaults to ".")'
        required: false
        type: string
        default: '.'
    secrets:
      token:
        description: 'GitHub token with packages:write permission'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Log in to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.token }}

      - name: 'Build and Push Image'
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
